server:
  port: 83
spring:
  application:
    name: consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
service-url:  #自己自定义注入的字段
  nacos-user-service: http://nacos-server